### ISSUE TITLE
Ciatzioni

### ISSUE THREAD

**Issue by tommasoltrz** [CasaJasmina/website#10]
Il layout delle citazioni (almeno nella sezione "projects" del sito) risulta diverso da come lo mostra wordpress in fase di editing.

![schermata 2015-10-28 alle 18 02 13](https://cloud.githubusercontent.com/assets/11644423/10796539/dfbb4d00-7d9e-11e5-991f-4f8860f04f05.png)
![schermata 2015-10-28 alle 18 02 00](https://cloud.githubusercontent.com/assets/11644423/10796540/dfc239e4-7d9e-11e5-82c8-61cad24f100c.png)

**Comment by lorenzoromagnoli** [comment]
closed!
