### ISSUE TITLE
Menue collapses  when size is large between 1025px e 1150

### ISSUE THREAD

**Issue by lorenzoromagnoli** [CasaJasmina/website#18]
@smellai can we remove this "large" size and make it always behave as very large when media-size>1025 

make it always behave as very large => with the extended top menue.

I'd like to avoid seeing this
<img width="1004" alt="screen shot 2016-01-04 at 17 46 31" src="https://cloud.githubusercontent.com/assets/2944758/12094815/20a8c986-b30b-11e5-8faf-f0acc400b05f.png">

**Comment by smellai** [comment]
I think the expanded navigation will not fit the space. Anyway just make a bit of tuning with the media queries https://github.com/CasaJasmina/website/blob/master/wp-content/themes/Arduino/style.css#L1158

**Comment by lorenzoromagnoli** [comment]
Fixed making the menu icon floating right.
